language: python
python:
  - 3.6
  - 2.7
cache: pip
env:
  - HOME=/home/travis
install:
  - pip install -U tox-travis
  - gem install jekyll
  - gem install pygments.rb
  - gem install kramdown
  - gem install s3_website
before_script:
  # - createdb judicious
  - pip install --upgrade pip
script:
  - tox
  - cd docs; jekyll build; cd ..
after_success:
  - cd docs; s3_website push; cd ..
deploy:
  - provider: heroku
    on:
      python: 3.6
    api_key:
      secure: J7i5aX+fTUFTfXE+rk/dmgC3jLOHX9Y8+tncSWXEz3Q5xOypFq6CwPgjebUKgkzsiaszW8prin32BWslbXYfmh3iWYMLXQicCF/uqe/X8B4k9JIAoFsTDVyi/iTNwueKWJcAoL1QzFJGoZaXk0NsyamnFrcGsAWn9HTHGN/qXN+zBhsxSSM5k3LRxe7skenl7yWd+AyHn7xEdiIF0v0P2d/NaBrrlzAxFC5bthdfTsx5IZCe6C5IXEhFxTzs4iwIGodUVeDHiZdWV5LPRE4eZIZTjAf5Tv7NL8fZMrY/lc57bAi9my+rA82U234c4UfCVCnJ2yCLEvNgB4CDorzOuJ1JRZhJMc+A4qLXypmsXDMXultZVGenQZ9ontIcgHxk4JRN6Tmz+i+tiYjvDpLF0kh6zDT0I+0lTnPGVuINQY9IcXDaFQOk8VMnJhVKqXaPVUXd6MhCd5prZQ/28LuYV7nSM/fkILRVZ7kHp/01Y5wgdtAKuytZs7ZhhGcSeo/5n/jyS1MsLyBqCZ9i/1YaBF9s/8OY6Eq3rz52FgvEj+4mhTreNlIUMv5LcbTBpEr4ck0iV6g3cdb7V3b1K6+xCGGclhUb2LwLkeUNqbT7SMkMuQie173F8HHuqXBcqCJ4f42Kq1qJ9bUFi5RAXBnJb7ip1cMjCSQhrxeSvx0ncVc=
    app: imprudent
  - provider: pypi
    user: suchow
    on:
      python: 3.6
      repo: suchow/judicious
      tags: true
    distributions: sdist bdist_wheel
    password:
      secure: U53L/lZTXu+9Ag+yzLyHZVj14lxmsBXsT5cJFtJZqrtLgxkBS2iHpFlCJ1x1kowfgJySR+91tbSsJ4akJAzjLLG56F9vQqtEEYsNeFfwnZTwdGYSPKZ8WsnQprCUtMwOlFY1V+oPrTFOtTAim77y000ClscSWxEO4/Q7o10KYSfEhuLdnUkEO/7gzFIo0YC0ACAHpirRnaIWLFGuXxnUk2zyf1k/zmNWm74pQwvNWDothbtXCP8wP3zaR+Ah6z0XqpLvqX1djW+sJFovat9E8RuvTQSe+111n+DEC2ODoSpFfC68MR429cpzIlx02ZePX7Ul0U0/Sbo1XNY+/pvBCmJ9Pl0P9g1zL6J0/lD1yIrppimN+Fi1r3oShmOMDora0QH/yyKKNhIVe2iTTUVgxw/l/X47QFCgUTRvHyMi4c3ZA1mOPF+i7wwB93KihtlMKZYT9fU097KY80EIkr27CS/mEUhmvlBCx2ATaCWs1ev/igjDwIHKURQT2+gHVCecQMG+qnhzTWIgQN+/UfZJX42kqAMNTI53KrIJNJH9JjTzbt8rgXX+WkFW8UcWNxf2DVYxn67cfUpq9GX17uGTj87E7Qp546iF57/HyK+465Sn7hcf8LRWt+HQJA1+riJ1FCku+g4bTUYEd1shKTW1qH5P+pcB5BbngARuUP0wC0A=
